//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dsp086 {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dsp086.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Difficult - Ballistic Missile.
        /// </summary>
        internal static string DifficultD {
            get {
                return ResourceManager.GetString("DifficultD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Easy - Nuclear Missile.
        /// </summary>
        internal static string DifficultE {
            get {
                return ResourceManager.GetString("DifficultE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Normal - Antitank Missile.
        /// </summary>
        internal static string DifficultN {
            get {
                return ResourceManager.GetString("DifficultN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distance target:.
        /// </summary>
        internal static string DistanceTarget {
            get {
                return ResourceManager.GetString("DistanceTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Must to type a number.
        /// </summary>
        internal static string ExceptionNumber {
            get {
                return ResourceManager.GetString("ExceptionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Input Angle(degree).
        /// </summary>
        internal static string InputAngle {
            get {
                return ResourceManager.GetString("InputAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Input difficult, type 1, 2 or 3:.
        /// </summary>
        internal static string InputDifficult {
            get {
                return ResourceManager.GetString("InputDifficult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Input your name:.
        /// </summary>
        internal static string InputName {
            get {
                return ResourceManager.GetString("InputName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Input speed(km/h).
        /// </summary>
        internal static string InputSpeed {
            get {
                return ResourceManager.GetString("InputSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Missile down at .
        /// </summary>
        internal static string Missile {
            get {
                return ResourceManager.GetString("Missile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Missile down at.
        /// </summary>
        internal static string MissileDown {
            get {
                return ResourceManager.GetString("MissileDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a shoot of player.
        /// </summary>
        internal static string NumShoot {
            get {
                return ResourceManager.GetString("NumShoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Want to play again?.
        /// </summary>
        internal static string PlayAgain {
            get {
                return ResourceManager.GetString("PlayAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Target destroyed at.
        /// </summary>
        internal static string TargetDestroyed {
            get {
                return ResourceManager.GetString("TargetDestroyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
